logging:
  level:
    root: info
    org.nutz: warn
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.29.128:3306/test1?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  aop:
    auto: true
    proxy-target-class: true
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


nutz:
  json:
    auto-unicode: false
    quote-name: true
    ignore-null: true
    null-as-emtry: true
    enabled: true
    mode: compact
  dao:
    runtime:
      create: true
      migration: false
      basepackage:
       - com.xhw.springbootnutz.model.mapped
       - BOOT-INF.classes.com.xhw.springbootnutz.model.mapped
    sqlmanager:
      paths:
        - sqls
server:
  port: 8070

minio:
  endpoint: https://store.gzeducard.com
  bucket: class-brand
  accessKey: IHYP5MXHEA21W30MJDBZ
  secretKey: 2nkQNKQAfJUIRABRtTQQuN255vHYnBOCvi3YACH9
  backurl: https://store.gzeducard.com

jpush:
  appKey: 959f8f408474be4392de31ee
  masterSecret: f4fa3c3259ca9806d6b7354d